### ISSUE TITLE
I can not pass props to components

### ISSUE THREAD

**Issue by tinvm** [vueComponent/ant-design-vue#3631]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
i have add components
return {
loading: false,
listOrders: [],
listProductionJobs: [],
components: {
header: {
cell: CustomCellHeader,
},
body: {
row: AddTooltip,
cell: CustomCell,
},
},
pagination: {
defaultPageSize: 30,
showSizeChanger: true,
pageSizeOptions: ['10', '20', '30', '50'],
},
};

but i can not pass variable to body.row

customRow(record, index) {
// console.log('3. record: ', record);
// console.log('8. index: ', index);
return {
props: {
record,
index,
},
on: {
click: () => {
console.log(index);
console.log(record);
},
mouseenter: () => {
console.log('go here');
},
},
render(createElement, context) {
console.log(context);
console.log(createElement);
return '';
},
};
},

### What does the proposed API look like?
i need add tooltips for tables row

**Comment by ShockwaVee** [comment]
I've also been trying something similar, here's a codepen.
https://codesandbox.io/s/draggable-table-forked-w2tn1?file=/src/App.vue
I need to add draggable to my table rows. I've used your solution on another issue @zkwolf , but it starts to break when you have expandable rows (I'm assuming because they get put in the same hierarchy as the main rows, instead of being a child of them).
Now I'm trying to make my own component in any way possible to include the expandable row in the row itself.
This is the way I managed to get something and have the draggable still working.

If this is the right way, I'm not sure how to get the props here (but I do get the component out)
```
row: {
            render: (createElement) => {
              // console.log("createElement", createElement);
              return <div>asd</div>;
            },
 ```

**Comment by ShockwaVee** [comment]
Any advice here?

**Comment by zkwolf** [comment]
You want to drag the expandedable row?

**Comment by ShockwaVee** [comment]
Yes, but the expandable row should be moved with its parent row. But you shouldn't be able to move just the expandable row around.
