### ISSUE TITLE
To use with vite2, how to automatically import on demand, can you give a demo in the document

### ISSUE THREAD

**Issue by yangss3** [vueComponent/ant-design-vue#3724]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
Automatically import components on demand in vite2

### What does the proposed API look like?
Give an example in document

**Comment by ifzm** [comment]
I also want to know，how to optimize size in vite :)

```js
index.js:6 You are using a whole package of antd, please use https://www.npmjs.com/package/babel-plugin-import to reduce app bundle size.
```

**Comment by zhenzhenChange** [comment]
This is my approach at this stage:

This is how it works with the `setup` option, but the style files are imported globally in `main.ts`, without `babel-plugin-import` or `vite-plugin-import`. (because I don't think it's necessary)

![import](https://s3.ax1x.com/2021/02/28/6CMFxK.png)

The first warning will be there but does not affect the use, but the second warning is a bit confusing as to why.

![warning](https://s3.ax1x.com/2021/02/28/6CMQRP.png)

**Comment by ajuner** [comment]
Try [vite-plugin-importer](https://github.com/ajuner/vite-plugin-importer)?

**Comment by ajuner** [comment]
Try [vite-plugin-importer](https://github.com/ajuner/vite-plugin-importer)?

**Comment by ifzm** [comment]
@ajuner good idea，support :+1: )

**Comment by mahy50** [comment]
Try [vite-plugin-style-import](https://github.com/anncwb/vite-plugin-style-import/blob/main/README.md)

> 由于 vite 本身已按需导入了组件库，因此仅样式不是按需导入的，因此只需按需导入样式即可。

**Comment by sky124380729** [comment]
> @tangjinzhou Why is this closed?

I also want to know,

**Comment by tjx666** [comment]
How to hide this warning? I have config it using `vite-plugin-components`

**Comment by ajuner** [comment]
> How to hide this warning? I have config it using `vite-plugin-components`

ref #4279
