### ISSUE TITLE
对话框可拖动

### ISSUE THREAD

**Issue by Jason-HuangTai** [vueComponent/ant-design-vue#516]
The issue which is not created via https://vuecomponent.github.io/issue-helper/ will be closed immediately.

---

注意：不是用 https://vuecomponent.github.io/issue-helper/ 或 http://ant-design-vue.gitee.io/issue-helper/ 创建的 issue 会被立即关闭。

**Comment by tangjinzhou** [comment]
Your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://vuecomponent.github.io/issue-helper/) to create an issue, thank you!  <br/><br/> 为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://vuecomponent.github.io/issue-helper/) 来创建 issue 以方便我们定位错误。谢谢配合！
