### ISSUE TITLE
form 缺少 统一的label-width设置，layout设置为horizontal问题较多

### ISSUE THREAD

**Issue by gdyxml2000** [vueComponent/ant-design-vue#522]
form 缺少 统一的label-width设置，layout设置为horizontal问题较多。

**Comment by gdyxml2000** [comment]
form的功能做的比较粗糙

**Comment by gdyxml2000** [comment]
通过插槽给a-modal 写正文，弹出模态框后，鼠标还能操作 已经被模态的 背景区域的内容。

**Comment by gdyxml2000** [comment]
日期组件、时间组件 通过插槽 显示 a-modal正文中，点击日期控件或者时间组件后，日期弹框在模态背景中显示，不在模态窗口显示，且无法点选，因为a-modal的z-index比较大，而日期时间组件没有设置z-index的地方。

**Comment by tangjinzhou** [comment]
Your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://vuecomponent.github.io/issue-helper/) to create an issue, thank you!  <br/><br/> 为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://vuecomponent.github.io/issue-helper/) 来创建 issue 以方便我们定位错误。谢谢配合！
