### ISSUE TITLE
气泡框首次弹出位置不对  第二次才正常

### ISSUE THREAD

**Issue by mirrormingzZ** [vueComponent/ant-design-vue#533]
![miv1 _0sj fs 06tpywwk](https://user-images.githubusercontent.com/40025981/53417326-54e9b180-3a10-11e9-88d8-be45e9a4bc01.png)
![p s3pyuwm h5z73va 7 cvk](https://user-images.githubusercontent.com/40025981/53417335-5adf9280-3a10-11e9-94ad-5ae80407d7d7.png)

**Comment by tangjinzhou** [comment]
Your issue has been closed because it does not conform to our issue requirements. Please use the [Issue Helper](https://vuecomponent.github.io/issue-helper/) to create an issue, thank you!  <br/><br/> 为了能够进行高效沟通，我们对 issue 有一定的格式要求，你的 issue 因为不符合要求而被自动关闭。你可以通过 [issue 助手](https://vuecomponent.github.io/issue-helper/) 来创建 issue 以方便我们定位错误。谢谢配合！
