### ISSUE TITLE
Focus input in popover dont work

### ISSUE THREAD

**Issue by Nisgrak** [vueComponent/ant-design-vue#6700]
- [X] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
3.2.20

### Environment
vue 3.2.36, chrome 114

### Reproduction link
[![Edit on CodeSandbox](https://codesandbox.io/static/img/play-codesandbox.svg)](https://codesandbox.io/s/basic-usage-ant-design-vue-3-2-20-forked-s3zc29)

### Steps to reproduce
Create an input as content of a popover
Use a template ref
Watch the template ref and call the focus function
Event with a nextTick it doesn't work

### What is expected?
Focus the input stored in the template ref

### What is actually happening?
Not focusing the input

**Comment by AdrianAbramczyk** [comment]
The same issue is present with a simple input element, so the issue is whether with the ant popover component or the way we trigger the focus with vue 3.

You can make it work with a `setTimeout`, therefore the focus is called too early somehow.
https://codesandbox.io/s/basic-usage-ant-design-vue-3-2-20-forked-w7nfdd

However, I can't find any hooks that would do the job.

It would be great to have a clean solution to this.

**Comment by AdrianAbramczyk** [comment]
Are you aware of this issue @tangjinzhou ?

**Comment by RaphaelColleterEvooq** [comment]
I have the same issue with ant select, with auto focus to true, it doesn't focus the select. I used the solution described by @AdrianAbramczyk with a `setTimeout` and it works. 

It would be great to fix it.

There was an issue here but closed for inactivity.
https://github.com/vueComponent/ant-design-vue/issues/5427
