### ISSUE TITLE
打开dialog时控制台报报错

### ISSUE THREAD

**Issue by StudentXiao** [vueComponent/ant-design-vue#7769]
- [ ] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### Version
4.2.3

### Environment
window12, chrome127.0.6533.73, vue3.4.29

### Reproduction link
[https://www.antdv.com/components/modal-cn](https://www.antdv.com/components/modal-cn)

### Steps to reproduce
1. 打开浏览器控制台
2. 打开一个Dialog

### What is expected?
控制台没有报错信息

### What is actually happening?
控制台有报错信息

---
错误信息：Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element

**Comment by StudentXiao** [comment]
可能和 vc-dialog -> Dialog.tsx -> onDialogVisibleChanged -> contentRef.value?.focus()  这里有关

**Comment by NorthWind17** [comment]
"ant-design-vue": "^1.7.8",
"vue": "^2.7.14",
在使用modal，popover的时候控制台也会报这个错
Blocked aria-hidden on a <div> element because the element that just received focus must not be hidden from assistive technology users. Avoid using aria-hidden on a focused element or its ancestor. Consider using the inert attribute instead, which will also prevent focus. For more details, see the aria-hidden section of the WAI-ARIA specification at https://w3c.github.io/aria/#aria-hidden. 
<div tabindex="0" aria-hidden="true" style="width: 0px; height: 0px; overflow: hidden;"></div>

**Comment by DaShengLeo** [comment]
这个问题已经有相似的提问，并且有暂时可以解决的css方案
