### ISSUE TITLE
Some queation about current project status and follow-up maintenance

### ISSUE THREAD

**Issue by hengistchan** [vueComponent/ant-design-vue#7836]
- [x] I have searched the [issues](https://github.com/vueComponent/ant-design-vue/issues)         of this repository and believe that this is not a duplicate.
        
        
### What problem does this feature solve?
There are a lot of PR unmerged in the project, 3.x and 4.x has compatibility issues with the Vue 3.4 3.5. Does the project have a Plan B, or is it going to be scrapped?

### What does the proposed API look like?
If don't expect further maintenance, I want the author to specify, not close these issues

**Comment by Owen-Tsai** [comment]
Sorry to put this up again. I chose AntdV for multiple projects/products across my org, one of the major reasons was that I really like AntD's design spec and the experience of interaction. We spent plenty of time modifying and extending it to better fit our need as well as to bypass issues that maintainers of this repo failed to fix/track. I think it's worth it at the moment since the community was pretty strong and active.

But by seeing the repo has no actual activity in the past months makes me feel **scared**. Due to severe finical problem my org planned to lay off **20%~25%** of personnel. Unlike mega corps, with almost 1/4 manpower lost we don't and won't have sufficient resources to keep an internally maintained version of our own; and we cannot just switch to another UI library in the foreseeable future since a major part of our enterprise-level assets are built with/on top of AntDV.

I have to admit that it's my fault during upfront investment period by choosing AntDV instead of Ant Group maintained AntD. But we've gone this far and there's no room for me o correct this error. So please, just inform us ahead of time if there's any change of the plan(i.e. shutting down the project, transit ownership, etc).

Best regards. And thanks for any efforts you guys made to the community. To small/tiny businesses like us you are literally heroes.
